### ISSUE TITLE
Better Version Number Generation

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/RobotBuilder#251] opened 2020-09-27 13:44 UTC
In order to make the automation scripts a little bit cleaner, we should replace the version capturing here:
https://github.com/wpilibsuite/RobotBuilder/blob/c2687bdce8540c76de538c058e310e5b0ab43842/src/main/java/robotbuilder/exporters/GenericExporter.java#L143-L163

With something more like what allwpilib uses:
https://github.com/wpilibsuite/allwpilib/blob/42993b15c6f22528e6ba24408bbecb9c9aa8a97a/wpilibj/build.gradle#L14-L43

**Comment by sciencewhiz** [comment] 2020-09-27 14:37
Duplicate of #212?

**Closed** 2020-09-27 16:29 UTC
